### ISSUE TITLE
Elro K1 connector is not connecting to HA

### ISSUE THREAD

**Issue by schoojan** [jbouwh/lib-elro-connects#17] opened 2022-08-20 12:03 UTC
Ik ben een nieuwe en dus geen ervaren gebruiker.
Volgens mij heb ik alles uitgevoerd maar krijg deze foutmelding terwijl de configuratie zegt succesvol te zijn.
![elroError1](https://user-images.githubusercontent.com/75940599/185745287-bbfb9d0e-d393-4a13-9389-d44bd5338845.jpg)

**Comment by jbouwh** [comment] 2022-08-20 12:32
Misschien kun je de homeassistant errorlog delen

**Comment by schoojan** [comment] 2022-08-21 08:04
Logger: homeassistant.config_entries
Source: config_entries.py:388
First occurred: 19 augustus 2022 om 19:49:59 (2 occurrences)
Last logged: 19 augustus 2022 om 19:50:07

  *   Config entry 'Elro Connects K1 Connector' for elro_connects integration not ready yet: Not received the expected result, cannot connect to hub 192.168.178.31 with id ST_ecfabc8f70e1. ('Expecting property name enclosed in double quotes: line 1 column 2 (char 1)',); Retrying in background
  *   Config entry 'VRV9517' for upnp integration not ready yet: Device not discovered: uuid:9bf6d6ca-1b77-4f61-88dd-0048cfda166b::urn:schemas-upnp-org:device:InternetGatewayDevice:2; Retrying in background


Van: Jan Bouwhuis ***@***.***>
Verzonden: zaterdag 20 augustus 2022 14:33
Aan: jbouwh/lib-elro-connects ***@***.***>
CC: schoojan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jbouwh/lib-elro-connects] Elro K1 connector is not connecting to HA (Issue #17)


Misschien kun je de homeassistant errorlog delen

**Comment by jbouwh** [comment] 2022-08-21 11:58
Interresting. It would help to see what the actual output is of the K1 connector.
It seems something is wrong with the JSON that is coming out.
Could you try the try to run the demo script  as `https://github.com/jbouwh/lib-elro-connects/blob/main/examples/fire_alarm_demo.py`. To install the library first use `pip install lib-elro-connects`.
The script takes and IP address and the connector ID. In you case: `192.168.178.31` `ST_ecfabc8f70e1`.

Further I'd like to know when devices are connected to the KA adapter.

**Comment by schoojan** [comment] 2022-08-21 14:39
Hi,

I have installed the library but how do I run the script?

Gr Jan

Van: Jan Bouwhuis ***@***.***>
Verzonden: zondag 21 augustus 2022 13:59
Aan: jbouwh/lib-elro-connects ***@***.***>
CC: schoojan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jbouwh/lib-elro-connects] Elro K1 connector is not connecting to HA (Issue #17)


Interresting. It would help to see what the actual output is of the K1 connector.
It seems something is wrong with the JSON that is coming out.
Could you try the try to run the demo script as https://github.com/jbouwh/lib-elro-connects/blob/main/examples/fire_alarm_demo.py. To install the library first use pip install lib-elro-connects.
The script takes and IP address and the connector ID. In you case: 192.168.178.31 ST_ecfabc8f70e1.

Further I'd like to know when devices are connected to the KA adapter.

**Comment by jbouwh** [comment] 2022-08-21 17:18
The script is installed in the package die under share/lib-elro-connects. With Linux it de pends on if the library is installed as root or user. As root the file can be found at `/usr/local/share/lib-elro-connects`. As user it is somewhere in the . local folder in your home path. You can also download the script manually from GitHub.

**Comment by schoojan** [comment] 2022-08-21 20:34
I have saved the github file in the custom_configuratin/elro_connect_examples/fire... etc.
I am not an experienced user so how do I start the script. I have some smokesendors and motion sensors connected to my K1. In the Elro app they are visible and "working". I have also more Elro Net switches I want to connect

Groetjes,

Jan van Schooten
06-42265315
________________________________

**Comment by jbouwh** [comment] 2022-08-21 21:25
The script is installed in the package die under share/lib-elro-connects. With Linux it de pends on if the library is installed as root or user. As root the file can be found at `/usr/local/share/lib-elro-connects`. As user it is somewhere in the . local folder in your home path. You can also download the script manually from GitHub.

> 

I suspect the motion detectors are the cause because I was not able to test them. To start the script just use the command `python pathtoscript.py attribute1 attribute2`.

**Comment by schoojan** [comment] 2022-08-23 15:50
2022-08-23 17:26:48.763 ERROR (SyncWorker_4) [homeassistant.components.python_script] Error loading script fire_alarm_demo.py: Line 26: AsyncFunctionDef statements are not allowed., Line 46: AsyncFunctionDef statements are not allowed., Line 134: "__name__" is an invalid variable name because it starts with "_"
2022-08-23 17:28:14.604 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2022-08-23 17:28:14.605 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2022-08-23 17:28:14.623 ERROR (SyncWorker_4) [homeassistant.components.python_script] Error loading script fire_alarm_demo.py: Line 26: AsyncFunctionDef statements are not allowed., Line 46: AsyncFunctionDef statements are not allowed., Line 134: "__name__" is an invalid variable name because it starts with "_"

__ bij naam weggehaald

2022-08-23 17:35:44.020 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547666219680] Error handling message: Service python_script.python_script.fire_alarm_dem2 does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'python_script.python_script.fire_alarm_dem2' (invalid_format)

IPadress en ST_naam ingevuld

2022-08-23 17:35:48.530 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547666219680] Error handling message: Service python_script.python_script.fire_alarm_dem2 does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'python_script.python_script.fire_alarm_dem2' (invalid_format)
2022-08-23 17:36:11.776 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547666219680] Error handling message: Service python_script.python_script.fire_alarm_dem2 does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'python_script.python_script.fire_alarm_dem2' (invalid_format)

Met quotes

if name == "main":
    # argv: 1 = IP_ADDRESS, 2 = API_KEY
    k1_hub = AlarmDemo("192.168….etc..","ST_ecfabc..etc…")
    asyncio.run(k1_hub.async_demo1())

2022-08-23 17:47:23.360 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547666219680] Error handling message: Service python_script.python_script.fire_alarm_dem2 does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']. Got 'python_script.python_script.fire_alarm_dem2' (invalid_format)

Gr Jan


Van: Jan Bouwhuis ***@***.***>
Verzonden: zondag 21 augustus 2022 19:19
Aan: jbouwh/lib-elro-connects ***@***.***>
CC: schoojan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jbouwh/lib-elro-connects] Elro K1 connector is not connecting to HA (Issue #17)


The script is installed in the package die under share/lib-elro-connects. With Linux it de pends on if the library is installed as root or user. As root the file can be found at /usr/local/share/lib-elro-connects. As user it is somewhere in the . local folder in your home path. You can also download the script manually from GitHub.

**Comment by jbouwh** [comment] 2023-07-13 14:02
I'll publish the merged fix supplied by @AmpioRosso . Ley me know if this helps.

**Comment by jbouwh** [comment] 2023-12-29 17:35
stale

**Closed by jbouwh** 2023-12-29 17:35 UTC
